version: "3.9"

services:

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drive_n_cook
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    image: backend
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=drive_n_cook
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  frontend-admin:
    image: frontend-admin
    ports:
      - "5173:5173"  # Port externe:Port interne du conteneur
    restart: unless-stopped

  frontend-franchise:
    image: frontend-franchise
    ports:
      - "5174:5174"  # Port externe:Port interne du conteneur
    restart: unless-stopped

volumes:
  mysql_data: